"""Core module - pure business logic, testable without I/O."""

from __future__ import annotations

from .config import (
    GetConfig,
    GetResult,
    IndexConfig,
    IndexResult,
    ListConfig,
    ListResult,
    ListSort,
    SearchConfig,
    SearchResult,
    SearchResultItem,
    SearchSource,
    SyncConfig,
    SyncResult,
    ResultSource,
)
from .get import (
    Get,
    get_cache_dir,
    get_cached_content,
    get_sync_dir,
    html_to_markdown,
    save_to_cache,
    url_to_sync_path,
)
from .get import local_content_exists as get_local_content_exists
from .list import (
    List,
    discover_pages,
    filter_by_pattern,
    sort_entries,
    format_as_json,
    format_as_yaml,
    format_as_xml,
    create_entry,
)
from .search import (
    DEFAULT_MAX_WORKERS,
    Search,
    discover_documentation_urls,
    discover_local_urls,
    extract_words_for_suggestions,
    PARALLEL_THRESHOLD,
    search_in_local,
)
from .sync import Sync

__all__ = [
    "DEFAULT_MAX_WORKERS",
    "Get",
    "GetConfig",
    "GetResult",
    "List",
    "PARALLEL_THRESHOLD",
    "Search",
    "SearchConfig",
    "SearchResult",
    "SearchResultItem",
    "SearchSource",
    "Sync",
    "SyncConfig",
    "SyncResult",
    "ResultSource",
    "create_entry",
    "discover_documentation_urls",
    "discover_local_urls",
    "discover_pages",
    "extract_words_for_suggestions",
    "filter_by_pattern",
    "format_as_json",
    "format_as_yaml",
    "format_as_xml",
    "get_cache_dir",
    "get_cached_content",
    "get_local_content_exists",
    "get_sync_dir",
    "html_to_markdown",
    "IndexConfig",
    "IndexResult",
    "ListConfig",
    "ListResult",
    "ListSort",
    "save_to_cache",
    "search_in_local",
    "sort_entries",
    "url_to_sync_path",
]
